export const personData  = [
    {"title":"a","desc":"lorem ipsum"},
    {"title":"b","desc":"lorem ipsum"},
    {"title":"c","desc":"lorem ipsum"},
    {"title":"d","desc":"lorem ipsum"},
    {"title":"e","desc":"lorem ipsum"},
    {"title":"f","desc":"lorem ipsum"},
    {"title":"g","desc":"lorem ipsum"},
    {"title":"h","desc":"lorem ipsum"},
    {"title":"i","desc":"lorem ipsum"},
    {"title":"j","desc":"lorem ipsum"},
    {"title":"k","desc":"lorem ipsum"},
    {"title":"l","desc":"lorem ipsum"},
    {"title":"m","desc":"lorem ipsum"},
    {"title":"n","desc":"lorem ipsum"},
    {"title":"o","desc":"lorem ipsum"},
    {"title":"p","desc":"lorem ipsum"},
    {"title":"q","desc":"lorem ipsum"},
    {"title":"r","desc":"lorem ipsum"},
    {"title":"s","desc":"lorem ipsum"},
    {"title":"t","desc":"lorem ipsum"},
    {"title":"q","desc":"lorem ipsum"},
    {"title":"v","desc":"lorem ipsum"},
]